### ISSUE TITLE
Resources tab updating

### ISSUE THREAD

**Issue by JordanHoang** [FlowWest/ukb-wq-app#16]
- [x] admin abilities to update resources tab
- [x] Weekly Bureau of Reclamation FASTA slides ?
- [x] Weekly USGS UKL Water Quality conditions map ?
- [x] Weekly Klamath Tribes water reports (water rights regulation) ?
- [x] OWRD upload weekly to Resources Tab 
- [x] Sonde Data (CSV file)

Resources Upload UI 
- [x] If admin signed in, show upload button and modal
- [x] Modal should ask user which Resource type it is. Dropdown of the 4/5 report types? 
- [x] Modal should have Report Date datepicker (database can automatically save Upload/Created At timestamp)
- [x] Modal should have File upload 
- [x]  If Sonde data, we need our http request data type to be CSV, else it will be PDF I believe

- Create new dynamoDB table that tracks all reports (@JordanHoang )

- on submit, we will POST new record of the report to that dynamoDB table and upload to S3 (similar to how we are doing for Reports).

- if Sonde data, we need our http request data type to be CSV, else it will be PDF I believe (might also just be able to use like file type from the file upload)
- 
- that dynamoDB table is also where we will query from to get all the reports for viewing 
- view buttons will take you to s3 link
- sonde data will download

"View All Reports page"

**Comment by JordanHoang** [comment]
@MaddeeRubenson Is the  Sonde Data (CSV file) another of the "Weekly Reports" card

**Comment by MaddeeRubenson** [comment]
Yes - it will be an upload of a CSV instead of a PDF. Should be formatted the same way as the weekly reports.
