### ISSUE TITLE
Complete Cognito sign in / sign out

### ISSUE THREAD

**Issue by JordanHoang** [FlowWest/ukb-wq-app#24]
- [x] persist user log in if active session
- [x] end AWS Cognito session on logout
- [x] ensure sign in functionality is shown in responsive views
- [x] "Show Password" functionality

- [x] need to handle password reset and newPasswordRequired

**Comment by wdwiii** [comment]
Do we still want a new password flow?

**Comment by JordanHoang** [comment]
@wdwiii 

the newPasswordRequired callback will be called by AWS when a new user signs in for the first time 

To replicate: 
- create new user on aws cognito portal
- go to sign in
- On sign in the newPasswordRequired callback will be invoked (it’s currently being commented out right now). In the callback we will need to have the UI go to the new password page and then on submit we will call the “completeNewPasswordChallenge” or whatever it’s called. Also in the commented code.
